// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
import { EQDataManager } from './src';

interface Env {
	EQ_DATA: DurableObjectNamespace<EQDataManager>;
	STATIC_FILES: R2Bucket
	CATALYST_JWK_URL: string
	CATALYST_APP_ID: string
}

